import React, { useEffect, useMemo, useState } from 'react'; import { View, Text, StyleSheet, TouchableOpacity } from 'react-native'; import { LinearGradient } from 'expo-linear-gradient'; import { Audio } from 'expo-av'; import BreathingCircle from '../components/BreathingCircle'; import Header from '../components/Header';
const techniques:{[k:string]:{pattern:{name:string;seconds:number}[]}}={ 'Box Breathing':{pattern:[{name:'Inhale',seconds:4},{name:'Hold',seconds:4},{name:'Exhale',seconds:4},{name:'Hold',seconds:4}]},'4-7-8 Breathing':{pattern:[{name:'Inhale',seconds:4},{name:'Hold',seconds:7},{name:'Exhale',seconds:8}]},'Coherent Breathing':{pattern:[{name:'Inhale',seconds:5},{name:'Exhale',seconds:5}]},'Calm Reset':{pattern:[{name:'Inhale',seconds:4},{name:'Exhale',seconds:6}]}};
export default function BreathingScreen({ navigation, route }: any) { const selected=route.params?.technique || '4-7-8 Breathing'; const pattern=useMemo(()=>techniques[selected].pattern,[selected]); const [running,setRunning]=useState(false); const [i,setI]=useState(0); const [left,setLeft]=useState(pattern[0].seconds); const [sound,setSound]=useState<Audio.Sound|null>(null);
 useEffect(()=>{ let t:any; if(running){ t=setInterval(()=>setLeft((v)=>{ if(v<=1){ setI((x)=>(x+1)%pattern.length); return pattern[(i+1)%pattern.length].seconds;} return v-1; }),1000);} return ()=>clearInterval(t);},[running,pattern,i]);
 useEffect(()=>{ setLeft(pattern[i].seconds); },[i,pattern]);
 useEffect(()=>()=>{ if(sound) sound.unloadAsync(); },[sound]);
 const play = async()=>{ if(!sound){ const {sound:s}=await Audio.Sound.createAsync(require('../sounds/ocean_1.mp3'),{isLooping:true,shouldPlay:true}); setSound(s);} else { await sound.replayAsync(); } };
 return <LinearGradient colors={['#020D35','#041A5E','#061E63']} style={s.bg}><View style={s.c}><Header title={selected} onBack={()=>navigation.goBack()} /><BreathingCircle step={pattern[i].name} countdown={left} duration={pattern[i].seconds*1000} isRunning={running} /><TouchableOpacity style={s.btn} onPress={()=>{setRunning(!running); if(!running) play();}}><Text style={s.bt}>{running?'Pause':'Start'}</Text></TouchableOpacity><TouchableOpacity style={s.end} onPress={()=>{setRunning(false);setI(0);setLeft(pattern[0].seconds);}}><Text style={s.et}>End Session</Text></TouchableOpacity></View></LinearGradient>; }
const s=StyleSheet.create({bg:{flex:1},c:{flex:1,padding:20,paddingTop:56},btn:{marginTop:22,backgroundColor:'#6F73FF',padding:16,borderRadius:28,alignItems:'center'},bt:{color:'#fff',fontSize:24,fontWeight:'700'},end:{marginTop:14,alignItems:'center'},et:{color:'#B8C8FA',fontSize:16}});
